import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div className={styles.grid}>
          {[
            {
              href: "https://tinyurl.com/4686673c",
              title: "Docs",
              content:
                "Find in-depth information about Next.js features and API.",
            },
            {
              href: "https://tinyurl.com/mrxwvfeh",
              title: "Learn",
              content:
                "Learn about Next.js in an interactive course with quizzes!",
            },
            {
              href: "https://tinyurl.com/yckz6kku",
              title: "Templates",
              content:
                "Discover and deploy boilerplate example Next.js projects.",
            },
            {
              href: "https://tinyurl.com/3tkm63kw",
              title: "Deploy",
              content:
                "Instantly deploy your Next.js site to a shareable URL with Vercel.",
            },
          ].map((item, index) => (
            <a
              key={index}
              href={item.href}
              className={styles.card}
              target="_blank"
              rel="noopener noreferrer"
            >
              <h2 className={inter.className}>
                {item.title} <span>-&gt;</span>
              </h2>
              <p className={inter.className}>{item.content}</p>
            </a>
          ))}
        </div>
      </main>
    </>
  );
}
